name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]  # Trigger deployment on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker
    - name: Build Docker image
      run: |
        docker build --platform linux/amd64 -t gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCR_IMAGE_NAME }}:latest .
    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCR_IMAGE_NAME }}:latest
    - name: Deploy/Update Cloud Run Job
      run: |
        gcloud run jobs describe "${{ secrets.CLOUD_RUN_JOB }}" --region ${{ secrets.GCP_REGION }} \
        && gcloud run jobs update "${{ secrets.CLOUD_RUN_JOB }}" \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCR_IMAGE_NAME }}:latest \
            --region ${{ secrets.GCP_REGION }} \
            --memory=4Gi --cpu=2 \
            --set-env-vars="DATABASE_URL=${{ secrets.DATABASE_URL }},R2_BUCKET_NAME=${{ secrets.R2_BUCKET_NAME }},OTHER_ENV=..." \
        || gcloud run jobs create "${{ secrets.CLOUD_RUN_JOB }}" \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCR_IMAGE_NAME }}:latest \
            --region ${{ secrets.GCP_REGION }} \
            --memory=4Gi --cpu=2 \
            --set-env-vars="${{ secrets.WORKER_ENV  }}"
      # This step deploys or updates a Cloud Run Job, not a Service.